### ISSUE TITLE
ComputeDomain daemonset pods might fail because of not working around node taints

### ISSUE THREAD

**Issue by jgehrcke** [NVIDIA/k8s-dra-driver-gpu#305]
In an environment where nodes have taints set a user might set tolerations on their workloads to counter those taints.

But then scheduling our ComputeDomain pods onto those very nodes might fail because they don't have comparable tolerations set.

Since ComputeDomain pods are tied to a user's workload the user knows best (and they _do_ set tolerations on their things), so we have to follow this intent. We seemingly can just use a catch-all toleration.

**Comment by jgehrcke** [comment]
```
$ kubectl explain pod.spec.tolerations

  key	<string>
    Key is the taint key that the toleration applies to. Empty means match all
    taint keys. If the key is empty, operator must be Exists; this combination
    means to match all values and all keys.

```

So maybe we want something like this:

```yaml
tolerations:
- operator: "Exists"
  effect: "NoSchedule"
- operator: "Exists"
  effect: "NoExecute"
- operator: "Exists"
  effect: "PreferNoSchedule"
```
