### ISSUE TITLE
EKS 1.32 DRA ERROR gpu: device class gpu.nvidia.com does not exist

### ISSUE THREAD

**Issue by vara-bonthu** [NVIDIA/k8s-dra-driver-gpu#338]
I encountered an error while trying to schedule GPU workloads using Dynamic Resource Allocation (DRA) on **Amazon EKS 1.32**. The key issue was a mismatch between the requested DeviceClass and what's available in the cluster.

`0/2 nodes are available: request gpu: device class gpu.nvidia.com does not exist. no new claims to deallocate, preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.`

The ResourceClaimTemplate is requesting a DeviceClass `gpu.nvidia.com`, but the cluster only has these DeviceClasses available:

```
compute-domain-daemon.nvidia.com
compute-domain-default-channel.nvidia.com
```

e.g.,

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test1

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test1
  name: single-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu.nvidia.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test1
  name: gpu-pod
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: gpu0
  resourceClaims:
  - name: gpu0
    resourceClaimTemplateName: single-gpu
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
```

NVIDIA Device plugin Installed

```sh
enable_nvidia_device_plugin = true
  nvidia_device_plugin_helm_config = {
    version = "v0.17.1"
    name    = "nvidia-device-plugin"
    values = [
      <<-EOT
        nodeSelector:
          accelerator: nvidia
        gfd:
          enabled: true
        nfd:
          gc:
            nodeSelector:
              accelerator: nvidia
          topologyUpdater:
            nodeSelector:
              accelerator: nvidia
          worker:
            nodeSelector:
              accelerator: nvidia
            tolerations:
              - key: nvidia.com/gpu
                operator: Exists
                effect: NoSchedule
              - operator: "Exists"
      EOT
    ]
  }
```

**DRA Driver deployed**

```sh
helm repo add nvidia https://helm.ngc.nvidia.com/nvidia 

helm repo update

helm install nvidia-dra-driver-gpu nvidia/nvidia-dra-driver-gpu \
--version="25.3.0-rc.2" \
--namespace nvidia-dra-driver-gpu \
--create-namespace \
-f values.yaml
```

```yaml
#values.yaml
nvidiaDriverRoot: /
nvidiaCtkPath: /usr/bin/nvidia-ctk

resources:
  gpus:
    enabled: true # set to false to disable experimental gpu support
  computeDomains:
    enabled: true

controller:
  nodeSelector: null
  affinity: null
  tolerations: []

kubeletPlugin:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "nvidia.com/gpu.present"
                operator: In
                values:
                  - "true"
  tolerations:
    - key: "nvidia.com/gpu"
      operator: Exists
      effect: NoSchedule

```

**Verification steps**

EKS Cluster shows the following output

```sh
kubectl api-resources | grep resource.k8s.io/v1beta1

deviceclasses         resource.k8s.io/v1beta1           false        DeviceClass
resourceclaims        resource.k8s.io/v1beta1           true         ResourceClaim
resourceclaimtemplates resource.k8s.io/v1beta1           true         ResourceClaimTemplate
resourceslices  resource.k8s.io/v1beta1           false        ResourceSlice
```

```sh
kubectl get deviceclasses                           
NAME                                        AGE
compute-domain-daemon.nvidia.com            23m
compute-domain-default-channel.nvidia.com   23m
```

**Comment by jgehrcke** [comment]
Cool. Closing this for now. Feel free to come back to us via issue or discussion.

**Comment by JiangJiaWei1103** [comment]
Hi @jgehrcke,

I try to deploy DRA `25.3.0-rc.4` to my on-prem K8s cluster, which has only a single node (with an RTX3090 GPU) serving as the control plane and the worker simultaneously. What I encounter is the same as above.

The following summarizes my current setup:

* `value.yaml`

```yaml
nvidiaDriverRoot: /

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
selectorLabelsOverride: {}
# Enable this option for validation
gpuResourcesEnabledOverride: true

allowDefaultNamespace: false

imagePullSecrets: []
image:
  repository: nvcr.io/nvidia/k8s-dra-driver-gpu
  pullPolicy: IfNotPresent
  # Note: an empty string is translated to the `appVersion` string from
  # the Helm chart YAML (effectively implementing the default value to be
  # the current version). Also note that a "v" is prefixed to the
  # `appVersion` value.
  tag: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

resources:
  gpus:
    # Disable this option
    enabled: false
  computeDomains:
    enabled: true
```

* `kubectl get deviceclasses`

```bash
NAME                                        AGE
compute-domain-daemon.nvidia.com            38m
compute-domain-default-channel.nvidia.com   38m
```

* `kubectl get resourceslices`

```bash
NAME                                      NODE      DRIVER                      POOL      AGE
rockwei-compute-domain.nvidia.com-z9csl   rockwei   compute-domain.nvidia.com   rockwei   39m
```

* `kubectl describe resourceslices rockwei-compute-domain.nvidia.com-z9csl`

```bash
Name:         rockwei-compute-domain.nvidia.com-z9csl
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  resource.k8s.io/v1beta1
Kind:         ResourceSlice
Metadata:
  Creation Timestamp:  2025-07-27T02:10:15Z
  Generate Name:       rockwei-compute-domain.nvidia.com-
  Generation:          1
  Owner References:
    API Version:     v1
    Controller:      true
    Kind:            Node
    Name:            rockwei
    UID:             6ea74d47-cd2d-49d9-a847-e0d6b68fb1be
  Resource Version:  244830
  UID:               db6a6fe9-faa5-418e-b02b-38802c8659ee
Spec:
  Devices:
    Basic:
      Attributes:
        Id:
          Int:  0
        Type:
          String:  daemon
    Name:          daemon-0
    Basic:
      Attributes:
        Id:
          Int:  0
        Type:
          String:  channel
    Name:          channel-0
  Driver:          compute-domain.nvidia.com
  Node Name:       rockwei
  Pool:
    Generation:            1
    Name:                  rockwei
    Resource Slice Count:  1
Events:                    <none>
```

Then, I manually deploy the device class by `kubectl apply -f templates/deviceclass-gpu.yaml`  and get:

```yaml
NAME                                        AGE
compute-domain-daemon.nvidia.com            44m
compute-domain-default-channel.nvidia.com   44m
gpu.nvidia.com                              7s
```

However, there's still no resourceslices corresponding to my RTX3090 GPU card. Thanks so much for the help!
