### ISSUE TITLE
GPU sharing: support Dynamic MIG (using DRA partitionable devices)

### ISSUE THREAD

**Issue by jgehrcke** [NVIDIA/k8s-dra-driver-gpu#361]
Dynamically provision MIG devices based on user requests (needs to be further spec'd out).

**Comment by jgehrcke** [comment]
> Naive usage of slice counters would not account for this asymmetry.

I started looking at https://gist.github.com/mortent/ddda505e2499c872549fa831dd2459c4 more carefully which models MIG device allocation for an A100. I know it might be imperfect and is just an example -- but it's linked from KEP 4815) and I want to study it properly. For tonight, I only had a superficial look, and it may not account for said asymmetry.

I need to look more in-depth again tomorrow. For now, full-device capacity model vs consumption model of 1g.5gb and 4g.20gb:

Full-device capacity model used in that gist (put on a single line for brevity):
```
    copy-engines:      quantity: "7"
    decoders:          quantity: "5"
    encoders:          quantity: "0"
    jpeg-engines:      quantity: "1"
    memory:            quantity: 40Gi
    memorySlice0:      quantity: "1"
    memorySlice1:      quantity: "1"
    memorySlice2:      quantity: "1"
    memorySlice3:      quantity: "1"
    memorySlice4:      quantity: "1"
    memorySlice5:      quantity: "1"
    memorySlice6:      quantity: "1"
    memorySlice7:      quantity: "1"
    multiprocessors:   quantity: "98"
    ofa-engines:       quantity: "1"
```

**1g.5gb** consumption model:
```
- attributes:
...
    profile:
      string: 1g.5gb
...
  consumesCounters:
  - counterSet: gpu-1-counter-set
    counters:
      copy-engines:
        value: "1"
      decoders:
        value: "0"
      encoders:
        value: "0"
      jpeg-engines:
        value: "0"
      memory:
        value: 4864Mi
      memorySlice6:
        value: "1"
      multiprocessors:
        value: "14"
      ofa-engines:
        value: "0"
  name: gpu-1-mig-1g.5gb-6
```

**4g.20gb** consumption model:
```
- attributes:
...
    profile:
      string: 4g.20gb
...
  consumesCounters:
  - counterSet: gpu-1-counter-set
    counters:
      copy-engines:
        value: "4"
      decoders:
        value: "2"
      encoders:
        value: "0"
      jpeg-engines:
        value: "0"
      memory:
        value: 19968Mi
      memorySlice0:
        value: "1"
      memorySlice1:
        value: "1"
      memorySlice2:
        value: "1"
      memorySlice3:
        value: "1"
      multiprocessors:
        value: "56"
      ofa-engines:
        value: "0"
  name: gpu-1-mig-4g.20gb-0-3
```

At first glance, it seems that _first_ consuming a `1g.5gb` (see below for its `consumesCounters`) would still leave space for a `4g.20gb` to be allocatable subsequently. I'll come back to this tomorrow.
